CFLAGS=`{pkg-config --cflags libgis}
LDFLAGS=`{pkg-config --libs libgis}
LIB=teapot.so
default:V: $LIB
%.so: %.o
	gcc $CFLAGS -fPIC -shared -o $target $prereq $LDFLAGS
%.o: %.c
	gcc $CFLAGS -fPIC -c -o $target $prereq
clean:V:
	rm -f *.o *.so
install:V:
	cp $LIB /usr/lib/gis/
uninstall:V:
	rm /usr/lib/gis/$LIB
